export const vaccines = [
  {
    id: 1,
    name: 'BBIBP-CorV',
    patent: 'Sinopharm',
    producer: 'China',
    method: 'viral inactivation methods',
    quantity: 420,
    uPrice: 17,
    approved: true,
  },
  {
    id: 2,
    name: ['Sputnik-V'],
    patent: 'Gamaleya',
    producer: ['Russia', 'India'],
    method: 'adenovirus',
    quantity: 130,
    uPrice: 12,
    approved: false,
  },
  {
    id: 3,
    name: 'AZD1222',
    patent: ['AstraZeneca', 'University of Oxford'],
    producer: ['UK', 'Bresil', 'India'],
    method: 'adenovirus',
    quantity: 5028,
    uPrice: 1.78,
    approved: false,
  },
  {
    id: 4,
    name: 'Tozinameran',
    patent: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    producer: ['Allemagne', 'USA'],
    method: 'ARN messager',
    quantity: 980,
    uPrice: 14,
    approved: true,
  },
  {
    id: 5,
    name: 'mRNA-1273',
    patent: ['Moderna', 'NIAID', 'BARDA'],
    producer: 'USA',
    method: 'ARN messager',
    quantity: 240,
    uPrice: 28,
    approved: false,
  },
  {
    id: 6,
    name: 'Ad26.COV2.S',
    patent: ['Johnson & Johnson', 'BIDMC'],
    producer: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    method: 'adenovirus',
    quantity: 110,
    uPrice: 31,
    approved: false,
  },
];
